name: itksnap
version: 4.2.2
# make sure to update the download link below: https://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.SNAP4
# they started including the build date: e.g. 20241202
architectures:
  - x86_64
structured_readme:
  description: |
    itksnap is an image viewer for DICOM and NII files and supports manual segmentation of data.
  example: itksnap
  documentation: http://www.itksnap.org/pmwiki/pmwiki.php
  citation: 'Paul A. Yushkevich, Joseph Piven, Heather Cody Hazlett, Rachel Gimpel Smith, Sean Ho, James C. Gee, and Guido Gerig. User-guided 3D active contour segmentation of anatomical structures: Significantly improved efficiency and reliability. Neuroimage 2006 Jul 1;31(3):1116-28.'
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - install: curl ca-certificates unzip binutils libqt5gui5 libopengl0 libxcb-cursor0 libxcb-cursor-dev
    - workdir: /opt/itksnap-{{ context.version }}
    - run:
        - curl -fsSL -o /example_data.zip https://www.nitrc.org/frs/download.php/750/MRI-crop.zip
        - unzip /example_data.zip
        - rm /example_data.zip
        - curl -fsSL --retry 5 https://sourceforge.net/projects/itk-snap/files/itk-snap/{{ context.version }}/itksnap-{{ context.version }}-20241202-Linux-x86_64.tar.gz | tar -xz --strip-components=1 -C /opt/itksnap-{{ context.version }}
    - environment:
        QT_QPA_PLATFORM: xcb
        PATH: $PATH:/opt/itksnap-{{ context.version }}/bin
    - deploy:
        bins:
          - itksnap
    - test:
        name: testScript
        script: |-
          #!/bin/bash
          itksnap --help
          exit 1
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAABatJREFUSEtVll1oHNcZhp/Zmd2dndFoNRvJWv00zY+sNJgmxWmaOImpb1pq9zaQi+BCctuLhNzVEDCEQMhVLmpKC6FXoSl2aUlrSlXk2JYtyW5DSYsdR5KVWFa90kqKpNXOanfn55TvyEe4A8P8nfN97/ee93vPWJcvX1YA+XyeOI6xbRullD7lXbfbxbIsfWZZRpIk+l7G5XI5/c48p2m6P1buC4UC1tWrV5UEMwHkKs9xp0O+WNRJ5JBEJrEElkPGkmXEjQaFMNTv5DDjNLCZmRmlUQHpjRtkYT+P/OqXdNKU+unT5IpFPUEOQasnr6/Tf/MG3tJdwslJrr/+Ov6xY/qbJDfjkYqmpqYU7TaFV17hB48+yj8Hh2hV+mgu3MY79Qvylco+oqzTofnuu5zY3IQwJOl2+XxhgfrPTtLzk+PYrquBpN0ujakpfvzRR1iTExPKvnCBvO/TmymWB6o4o6NkM1P0FYt0jh3TVMXtNrVPPmGwVqOgFNuzs9yt9OOGZQ4ePUrD9/GOHNG03T5/nsrcHO7SEtalS5eU8Cw0zb/zDgdLJbK33tKlGp4dx9kvW8qvffoprTNnePjNN7Gef16vkyyqUCjz5F6uye7ufYqEX0F46hRD779Pel9BhnOjIiOGrdOnKZ48iTc2ts+7jJXAAkbUKEmjL77AunLlilaRKGH9ww+pvvEGcZLoAQaNWWB5lmRbJ05Q+uADiuPj/4fYSFYUJxKtv/021sWLF5VMLL32GrU7dyh9/DG5MNQJjCoElaGgffaspqcShhTOn2d3d1f3hKHHVKI2NkhffRVrdnZWyUvzwWhZkJrAnU5HIzJr0mg0dCXlcnk/uKxhq9WiVCrRbrdxXVeDtCYmJpTv+3qRTQDD5YPUmAoksCQU1KbrJZjQYoAYF5DvWkVSpkyUgVLJfpeCTux5ng5gaBBK5RSkZq0M7wJEKgmCYM9GdKOZtr/Pj6hAEmqpJcm+78hkI0njO0bCxpckhMwxgrDe+/2i6li9hNkdvjvYQKkczaYYR4zvo9dBSt3cTMgyhedlOM6emqLIIo4VxWJCuexpxN1uSrOpSFPBrbB+/odUlXKKKFOMx59R7VX8I3mWA76iv3WDx3s2cQou89khUjIe+uY65Z49J/0s9yJ36zFJZnPcn8TzSmx0Av7cPoSbOTzco7De+3usRlbP3bfmDsHg4/wrfZqHegsEHgTL01T8jO3wMK22wl2dJgzyfNUcgdGDLE7+jd5nj2Pf+gvPPOHTiAMuNA5R7q7hLJ7FOnMtVTRWcIkZiBdxgz4WnKeJG+sMVEOcJKJUm8F65AVUziaenybwbJojR9lpKpJbf6I19jIqWuNJ6yZdK2TOfopcc4XH+DfWby7XVScr4ga9ZKuLDOVXiQ48R7SyQDcuMPLkt1meu8fogR5yBZt4cRrHr9AefIral18y5t1juXSYmDxDjeu4foVacJhSCZwce32w07apD7yIX7AJ6tMw+hJb9+aotBdIqt9jt1ClE6XYdkxQn8EKqkR9T9Bptal4iqTgshlBuHYN33XZCJ9BRU22vvoP1m8vrChlK0rlKs3aPFV7lXT0BXZqkuBrEqeX1tBzbLcVabTL4PYM2/1HSJwSbNwmS8W3HLzRMVZu3mI8bNAZPkxzZQ13Yxrr19cyNVC2qN9rUfrvXzkw+i22+r7PTm2e4ew2PT0+rVixVH4J4jb5r6+SO/gjlG2Rv/k7+vsrJElKPP5TtrcyvNol8t/5Id8s1RiKP8c6d+6PKo4zPC9PEPRIy7G8vKI1PTw8oLtY7wG1daKoRaVSZnNzizTNMTwcIjYjPbG2ts3OTgPXLRJFEbmcw8jIwJ5VSDOZPwZpKulE6VizH5hOf9BdpdtN9xpTlO6W+WY/0Bb0oFUYWxBfkYHGBmSi2chNYvMXYqxans1OZn5/JM7/AEQ2XsKuszdzAAAAAElFTkSuQmCC
gui_apps:
  - name: "itksnapGUI"
    exec: "itksnap"
categories:
  - visualization
readme: |-
  ----------------------------------
  ## itksnap/{{ context.version }} ##

  itksnap is an image viewer for DICOM and NII files and supports manual segmentation of data.

  Example:
  ```
  itksnap
  ```

  More documentation can be found here: http://www.itksnap.org/pmwiki/pmwiki.php

  Citation:
  ```
  Paul A. Yushkevich, Joseph Piven, Heather Cody Hazlett, Rachel Gimpel Smith, Sean Ho, James C. Gee, and Guido Gerig. User-guided 3D active contour segmentation of anatomical structures: Significantly improved efficiency and reliability. Neuroimage 2006 Jul 1;31(3):1116-28.
  ```

  To run container outside of this environment: ml itksnap/{{ context.version }}

  ----------------------------------
copyright:
  - license: LGPL-3.0-only
    url: https://github.com/pyushkevich/itksnap?tab=GPL-3.0-1-ov-file#readme


# needed for centos, but libcurl error: libX11 libglvnd-glx libglvnd-opengl libxkbcommon libglvnd-egl fontconfig dbus-libs

 #  --env QT_QPA_PLATFORM="xcb" forces xcb under wayland - this was otherwise causing a library error

# This is to fix qt library error in centos 7:
# --run="find /opt/itksnap-4.0.2/ -name '*.so' | xargs strip --remove-section=.note.ABI-tag" \
# https://github.com/microsoft/WSL/issues/3023



# # Troubleshooting:
# export QT_QPA_PLATFORM=wayland
# export QT_DEBUG_PLUGINS=1
# itksnap
# apt update
# apt install -y mlocate
# updatedb
# locate libQt6Core.so.6