name: clinica
version: 0.10.0
architectures:
  - x86_64
structured_readme:
  description: |-
    Software platform for clinical neuroimaging studies
    Clinica is a software platform for clinical research studies involving patients with neurological and psychiatric diseases and the acquisition of multimodal data (neuroimaging, clinical and cognitive evaluations, genetics...), most often with longitudinal follow-up.
  example: ml clinica
  documentation: www.clinica.run/
  citation: 'Routier, A., Burgos, N., Díaz, M., Bacci, M., Bottani, S., El-Rifai O., Fontanella, S., Gori, P., Guillon, J., Guyot, A., Hassanaly, R., Jacquemont, T., Lu, P., Marcoux, A., Moreau, T., Samper-González, J., Teichmann, M., Thibeau-Sutre, E., Vaillant G., Wen, J., Wild, A., Habert, M.-O., Durrleman, S., and Colliot, O.: Clinica: An Open Source Software Platform for Reproducible Clinical Neuroscience Studies Frontiers in Neuroinformatics, 2021 doi:10.3389/fninf.2021.689675'
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - environment:
        LD_LIBRARY_PATH: ''
    - template:
        name: miniconda
        version: py310_25.5.1-0
        install_path: /opt/miniconda
        conda_install: python=3.10
        pip_install: clinica
    - template:
        name: fsl
        version: 6.0.7.16
    - template:
        name: spm12
        version: r7771
    - template:
        name: freesurfer
        version: 7.4.1
    - template:
        name: ants
        version: 2.4.3
    - template:
        name: mrtrix3
        version: 3.0.4
    - template:
        name: dcm2niix
        version: latest
    - deploy:
        path: []
        bins:
          - clinica
    - test:
        name: testScript
        script: |-
          #!/bin/bash
          clinica --version
          fslmaths --version
          recon-all --version
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAA5VJREFUSEuVlklME1Ecxr/HFBE6UEtFJAKCRlFRrAUUUWk0IRgSThDlIAnhoHGJS1yiXj3h1YPGmBiXuMQlKhBCkIOiYjFiRNRE1qIotVq7GW2xM+a90rGdeaC2aTKZefN+/+97/6Xk+L21sizLiP4BgCTJ+O4OYqYogMSBPaef6HWhCRn+b0GIqTqAxD6LrCfH7pawN9UQKSTBMfwDySYdElN0mgDoet/XILzOINIXJgJEGwDdlxy9s2ZKgP2VD/EJBBmL9JDpd1JpROGHN378CkrIWq5XAJIkxShlgNgXwwuogqEeD4swf2MqhHgSo2IiEMKr+9+QMkeHHHMyA0TvE7kmR24XT6lg+IUPbztd2LAtA3qjLgyejJCCOy+NI299CuabxaktogAemSqggI5z77F5TzYy8pLoSbEoaQJ8eO1H++mPsNanxwA0Fh2+VaQBhH5JeNflRuspO4uafkq3pqOgIhU0mfo6XHh8xaE827R9LhYUi9xsI4duFmoskkIyA5DBfLS0tMDn86GgbB6s9RlMBbWmu20YJpMJ1dXVcM9+EgOIdoQcvGHhKuh/6oYwXIDm5mYWaUnpaqStG2dR2u+LePn8DbtfU1MDl/ERcov1fAXRgAiZKogG+P1+puTE2Z2IE4C9W06itrYWoihyATEKDlw3cy3qf+qBbiSsoKmpCVarFQaDgUXtcDhgs9lQVVXFAF+Nncgt+qPgrwB6yP02D+JHVjJARUUF2traYLFY4Ha7MTQ0hPLycrS3tzPAl1kUkIQ4gShprNTB/msrNYVGLRqgALuZAbKystDb24vW1lZ4PB7U1dUhOzsbLpcrDDA8RE5RknIGMQr2XS3QWEQVDNi8mDH6B9DY2IjKykoEAgF0dXWhoaFBATgND5BTGFagbppk75UVfEC3FwmjqxQFaWlp6OnpYWdQVlaGvr4+BfA5hQISNQAKYwB1JTMF3V7MsJtZ9mRmZmJsbAxerxeCIECv18NoNDIArQMntagwkZ+mey7ncxUMPvOh48wnpVqnu1hfb8J8y0y+RRSgVkB7jXs8AJ9zgvUdNi8kGc6Rn6AJMDs3AQST9wHoU+OQPIc2w3Cvip4vZPelZdx2rT4sNmC+hIGiSVA2Ujc3DWDXxaUai3gTLvIi7bLq8TjderLzwhJuu1Y2VE0onjLewFIKTQ3gSebNi38NgOw4v/i/LFL/OVB7rik0HmA6yX/bUB3Ab9gvR72mBXL6AAAAAElFTkSuQmCC
readme: |-
  ----------------------------------
  ## clinica/0.10.0 ##

  Software platform for clinical neuroimaging studies
  Clinica is a software platform for clinical research studies involving patients with neurological and psychiatric diseases and the acquisition of multimodal data (neuroimaging, clinical and cognitive evaluations, genetics...), most often with longitudinal follow-up.

  Example:
  ```
  ml clinica
  ```

  More documentation can be found here: www.clinica.run/

  Citation:
  ```
  Routier, A., Burgos, N., Díaz, M., Bacci, M., Bottani, S., El-Rifai O., Fontanella, S., Gori, P., Guillon, J., Guyot, A., Hassanaly, R., Jacquemont, T., Lu, P., Marcoux, A., Moreau, T., Samper-González, J., Teichmann, M., Thibeau-Sutre, E., Vaillant G., Wen, J., Wild, A., Habert, M.-O., Durrleman, S., and Colliot, O.: Clinica: An Open Source Software Platform for Reproducible Clinical Neuroscience Studies Frontiers in Neuroinformatics, 2021 doi:10.3389/fninf.2021.689675
  ```

  To run container outside of this environment: ml clinica/0.10.0

  ----------------------------------
categories:
  - workflows
