name: b0map
version: 1.0.0
architectures:
    - x86_64

files:
    - name: b0map.py
      filename: b0map.py

build:
    kind: neurodocker
    base-image: ubuntu:22.04
    pkg-manager: apt

    directives:
        - environment:
              DEBIAN_FRONTEND: noninteractive
        - install: bzip2 ca-certificates git wget build-essential python3-pip python-is-python3

        # Add OpenRecon macro
        - include: macros/openrecon/neurodocker.yaml

        #BET2 application
        - install:
              - gcc-aarch64-linux-gnu cmake make build-essential

        - workdir: /opt/code
        - run:
              - git clone https://github.com/Bostrix/FSL-BET2
              - cd FSL-BET2
              - mkdir build
              - cd build
              - cmake ..
              - make

        - environment:
              PATH: ${PATH}:/opt/code/FSL-BET2/bin

        #openrecon application
        - copy: b0map.py /opt/code/python-ismrmrd-server/b0map.py

deploy:
    path:
        - /opt/code/FSL-BET2/bin

readme: |-
    ----------------------------------
    ## b0map/{{ context.version }} ##
    This open recon tool will compute a b0 map based on two GRE images

    you can setup the builder environment with:
    ```bash
    python3 -m venv env
    source env/bin/activate
    pip install -e .
    ```

    you can build this recipe with:
    ```bash
    source env/bin/activate
    ./builder/build.py generate b0map --recreate --build --login --architecture x86_64
    ```

    or shorter: open the build.yaml file in the local terminal and run:
    ```
    sf-login 
    ```
    ----------------------------------
