name: ants
version: 2.6.0 # https://github.com/ANTsX/ANTs/releases

copyright:
  - license: Apache-2.0
    url: https://github.com/afni/afni?tab=License-1-ov-file

architectures:
  - x86_64
build:
  kind: neurodocker

  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - template:
        name: ants
        make_opts: -j8
        method: source
        version: "{{ context.version }}"
    - install:
        - bc

deploy:
  path:
    - /opt/ants-{{ context.version }}/bin
    - /opt/ants-{{ context.version }}/Scripts

readme: |
  ----------------------------------
  ## ants/{{ context.version }} ##

  ANTs extracts information from complex datasets that include imaging. Paired with ANTsR, ANTs is useful for managing, interpreting and visualizing multidimensional data. ANTs is popularly considered a state-of-the-art medical image registration and segmentation toolkit. ANTsR is an emerging tool supporting standardized multimodality image analysis. ANTs depends on the Insight ToolKit (ITK), a widely used medical image processing library to which ANTs developers contribute. A summary of some ANTs findings and tutorial material (most of which is on this page) is here.\

  Example:

  ```
  antsRegistration\
  ```

  More documentation can be found here: https://issuu.com/brianavants/docs/ants2

  To run container outside of this environment: ml ants/{{ context.version }}

  Citation:
  ```
  Avants BB, Tustison NJ, Song G, Cook PA, Klein A, Gee JC. A reproducible evaluation of ANTs similarity metric performance in brain image registration. Neuroimage. 2011 Feb 1;54(3):2033-44. doi: 10.1016/j.neuroimage.2010.09.025. Epub 2010 Sep 17. PMID: 20851191; PMCID: PMC3065962.
  ```

  License: Apache 2 License, https://github.com/ANTsX/ANTs?tab=Apache-2.0-1-ov-file#readme
  ----------------------------------

categories:
  - "image registration"
  - "structural imaging"
  - "image segmentation"
